name: Convert Markdown to HTML and publish

on:
  push:
    paths:
      - 'docs/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown files to HTML
        run: |
          for file in docs/*.md; do
            filename=$(basename "$file" .md)
            pandoc "$file" -o "public/$filename.html"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public